### ISSUE TITLE
If use ajax to add the template, body will be clear

### ISSUE THREAD

**Issue by Little-Fan** [softwarespot/jquery-handlebars#6]
Version: 1.3.7  

 Line Number 253
               var _$body = $('body');

```
           // When the external template has has successfully loaded
            _$body.load(url, function load() {
                defer.resolve();
            });
```

**Comment by softwarespot** [comment]
Thanks for reporting, seems I misunderstood the purpose of .load(). Now I have re-read the documentation I see I should use a different method. A fix will come later on today as well as a new release.
