### ISSUE TITLE
Ajax Load Doesnt Work

### ISSUE THREAD

**Issue by mfeerick** [softwarespot/jquery-handlebars#7]
When attempting to use the ajax- version of the script.

The $.getScript is failing with a parse error as the $.getScript is expecting javascript to be returned which it then calls eval() on, however the template is not javascript, even in your ajax example.

**Comment by softwarespot** [comment]
Thanks for reporting. Hopefully this fixed your issue. 

In all honesty my coding style has changed dramatically in the last year, so expect a lot of refactoring
